from parameter_extraction.create_tables_attributes import create_tables_idx_attributes
from parameter_extraction.transfer_raw_attributes import transfer_raw_table_to_attributes

from parameter_extraction.create_tables_options import create_tables_idx_options
from parameter_extraction.transfer_raw_options import transfer_raw_table_to_options


