TON_ORIGIN = "ТСН"     # TERRITORIAL OUTLAY NORMATIVE
PNWC_ORIGIN = "НЦКР"   # PRICE NORMATIVE FOR WORK COMPLEXES
POM_ORIGIN = "ПСМ"     # PROJECT OUTLAY MODULE

MAIN_RECORD_CODE = "0.0"

EQUIPMENTS_ORIGIN = "оборудование"
MONITORING_ORIGIN = "мониторинг"

LOCATIONS = ("home", "office")

CONFIG_FILE_NAME = 'config_quotes_parsing.json'
DB_FILE_NAME = 'Normative.sqlite3'